-- CreateEnum
CREATE TYPE "CurrencyCodes" AS ENUM ('AUD', 'AZN', 'GBP', 'AMD', 'BYN', 'BGN', 'BRL', 'HUF', 'VND', 'HKD', 'GEL', 'DKK', 'AED', 'USD', 'EUR', 'EGP', 'INR', 'IDR', 'KZT', 'CAD', 'QAR', 'KGS', 'CNY', 'MDL', 'NZD', 'NOK', 'PLN', 'RON', 'XDR', 'SGD', 'TJS', 'THB', 'TRY', 'TMT', 'UZS', 'UAH', 'CZK', 'SEK', 'CHF', 'RSD', 'ZAR', 'KRW', 'JPY', 'RUB');

-- CreateTable
CREATE TABLE "Currency" (
    "id" SERIAL NOT NULL,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,
    "code" "CurrencyCodes" NOT NULL,
    "name" TEXT NOT NULL,

    CONSTRAINT "Currency_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "RubExchageRate" (
    "id" SERIAL NOT NULL,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,
    "date" DATE NOT NULL,
    "AUD" DOUBLE PRECISION NOT NULL,
    "AZN" DOUBLE PRECISION NOT NULL,
    "GBP" DOUBLE PRECISION NOT NULL,
    "AMD" DOUBLE PRECISION NOT NULL,
    "BYN" DOUBLE PRECISION NOT NULL,
    "BGN" DOUBLE PRECISION NOT NULL,
    "BRL" DOUBLE PRECISION NOT NULL,
    "HUF" DOUBLE PRECISION NOT NULL,
    "VND" DOUBLE PRECISION NOT NULL,
    "HKD" DOUBLE PRECISION NOT NULL,
    "GEL" DOUBLE PRECISION NOT NULL,
    "DKK" DOUBLE PRECISION NOT NULL,
    "AED" DOUBLE PRECISION NOT NULL,
    "USD" DOUBLE PRECISION NOT NULL,
    "EUR" DOUBLE PRECISION NOT NULL,
    "EGP" DOUBLE PRECISION NOT NULL,
    "INR" DOUBLE PRECISION NOT NULL,
    "IDR" DOUBLE PRECISION NOT NULL,
    "KZT" DOUBLE PRECISION NOT NULL,
    "CAD" DOUBLE PRECISION NOT NULL,
    "QAR" DOUBLE PRECISION NOT NULL,
    "KGS" DOUBLE PRECISION NOT NULL,
    "CNY" DOUBLE PRECISION NOT NULL,
    "MDL" DOUBLE PRECISION NOT NULL,
    "NZD" DOUBLE PRECISION NOT NULL,
    "NOK" DOUBLE PRECISION NOT NULL,
    "PLN" DOUBLE PRECISION NOT NULL,
    "RON" DOUBLE PRECISION NOT NULL,
    "XDR" DOUBLE PRECISION NOT NULL,
    "SGD" DOUBLE PRECISION NOT NULL,
    "TJS" DOUBLE PRECISION NOT NULL,
    "THB" DOUBLE PRECISION NOT NULL,
    "TRY" DOUBLE PRECISION NOT NULL,
    "TMT" DOUBLE PRECISION NOT NULL,
    "UZS" DOUBLE PRECISION NOT NULL,
    "UAH" DOUBLE PRECISION NOT NULL,
    "CZK" DOUBLE PRECISION NOT NULL,
    "SEK" DOUBLE PRECISION NOT NULL,
    "CHF" DOUBLE PRECISION NOT NULL,
    "RSD" DOUBLE PRECISION NOT NULL,
    "ZAR" DOUBLE PRECISION NOT NULL,
    "KRW" DOUBLE PRECISION NOT NULL,
    "JPY" DOUBLE PRECISION NOT NULL,

    CONSTRAINT "RubExchageRate_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "ThbExchageRate" (
    "id" SERIAL NOT NULL,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,
    "date" TEXT NOT NULL,
    "AUD" DOUBLE PRECISION NOT NULL,
    "AZN" DOUBLE PRECISION NOT NULL,
    "GBP" DOUBLE PRECISION NOT NULL,
    "AMD" DOUBLE PRECISION NOT NULL,
    "BYN" DOUBLE PRECISION NOT NULL,
    "BGN" DOUBLE PRECISION NOT NULL,
    "BRL" DOUBLE PRECISION NOT NULL,
    "HUF" DOUBLE PRECISION NOT NULL,
    "VND" DOUBLE PRECISION NOT NULL,
    "HKD" DOUBLE PRECISION NOT NULL,
    "GEL" DOUBLE PRECISION NOT NULL,
    "DKK" DOUBLE PRECISION NOT NULL,
    "AED" DOUBLE PRECISION NOT NULL,
    "USD" DOUBLE PRECISION NOT NULL,
    "EUR" DOUBLE PRECISION NOT NULL,
    "EGP" DOUBLE PRECISION NOT NULL,
    "INR" DOUBLE PRECISION NOT NULL,
    "IDR" DOUBLE PRECISION NOT NULL,
    "KZT" DOUBLE PRECISION NOT NULL,
    "CAD" DOUBLE PRECISION NOT NULL,
    "QAR" DOUBLE PRECISION NOT NULL,
    "KGS" DOUBLE PRECISION NOT NULL,
    "CNY" DOUBLE PRECISION NOT NULL,
    "MDL" DOUBLE PRECISION NOT NULL,
    "NZD" DOUBLE PRECISION NOT NULL,
    "NOK" DOUBLE PRECISION NOT NULL,
    "PLN" DOUBLE PRECISION NOT NULL,
    "RON" DOUBLE PRECISION NOT NULL,
    "XDR" DOUBLE PRECISION NOT NULL,
    "SGD" DOUBLE PRECISION NOT NULL,
    "TJS" DOUBLE PRECISION NOT NULL,
    "TRY" DOUBLE PRECISION NOT NULL,
    "TMT" DOUBLE PRECISION NOT NULL,
    "UZS" DOUBLE PRECISION NOT NULL,
    "UAH" DOUBLE PRECISION NOT NULL,
    "CZK" DOUBLE PRECISION NOT NULL,
    "SEK" DOUBLE PRECISION NOT NULL,
    "CHF" DOUBLE PRECISION NOT NULL,
    "RSD" DOUBLE PRECISION NOT NULL,
    "ZAR" DOUBLE PRECISION NOT NULL,
    "KRW" DOUBLE PRECISION NOT NULL,
    "JPY" DOUBLE PRECISION NOT NULL,
    "RUB" DOUBLE PRECISION NOT NULL,

    CONSTRAINT "ThbExchageRate_pkey" PRIMARY KEY ("id")
);

-- CreateIndex
CREATE UNIQUE INDEX "Currency_code_key" ON "Currency"("code");

-- CreateIndex
CREATE UNIQUE INDEX "RubExchageRate_date_key" ON "RubExchageRate"("date");

-- CreateIndex
CREATE UNIQUE INDEX "ThbExchageRate_date_key" ON "ThbExchageRate"("date");
