version: '3.1'
services: 
  db: 
    container_name: db
    image: postgres
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=pass
      - POSTGRES_DB=db
    ports:
      - 5433:5432
    restart: always
  app:
    container_name: app
    build: 
      context: ./
    env_file:
      - .env
    environment:
      - DATABASE_URL=postgres://user:pass@db:5432/db?sslmode=disable
    ports:
      - 3000:3000
    restart: always
